import { RunningShoe } from '../types';

/**
 * 41개 프리미엄 러닝화 신규 컬렉션
 * - 목표 마일리지: 레이싱화 300km, 나머지(데일리, 스피드, 장거리, 트레일) 600km 통일
 * - 현재 주행거리: 0km 초기화
 */
export const INITIAL_RUNNING_SHOES: RunningShoe[] = [
  // 1. 나이키
  {
    id: 'shoe-nike-vaporfly-4',
    name: '나이키 베이퍼플라이 4',
    brand: 'Nike',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '업그레이드된 줌X 폼과 카본 플라이플레이트의 초경량 레이싱화. 10K부터 풀코스 PB 달성을 위한 최고의 선택.',
    createdAt: '2026-03-01',
  },
  {
    id: 'shoe-nike-vomero-plus',
    name: '나이키 보메로 플러스',
    brand: 'Nike',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '풍성한 줌X 쿠셔닝과 안정성이 결합된 최고급 맥스쿠션 데일리 트레이너. 매일 신어도 발목에 부담이 없음.',
    createdAt: '2026-02-15',
  },
  {
    id: 'shoe-nike-vomero-18-gtx',
    name: '나이키 보메로 18 고어텍스',
    brand: 'Nike',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '우천 및 악천후 러닝에서도 완벽한 방수를 자랑하는 전천후 든든한 쿠션화.',
    createdAt: '2026-01-20',
  },
  {
    id: 'shoe-nike-alphafly-3-volt',
    name: '나이키 알파플라이 3 볼트',
    brand: 'Nike',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '시선 강탈 볼트 컬러! 듀얼 에어팟과 카본 로드의 압도적인 에너지 리턴으로 풀코스 후반부 페이스를 굳건히 지켜줌.',
    createdAt: '2026-03-15',
  },
  {
    id: 'shoe-nike-alphafly-3-glam',
    name: '나이키 알파플라이 3 글램',
    brand: 'Nike',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '감각적인 글램 스페셜 컬러웨이. 발을 감싸는 아톰니트 3.0의 일체감과 지면 반발력이 경이로움.',
    createdAt: '2026-04-01',
  },
  {
    id: 'shoe-nike-streakfly-2',
    name: '나이키 스트릭플라이 2',
    brand: 'Nike',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '트랙 인터벌 및 5K~10K 타임트라이얼에 특화된 초경량 스피드화. 발의 기민한 반응성과 지면 감각이 탁월함.',
    createdAt: '2026-02-28',
  },
  {
    id: 'shoe-nike-pegasus-trail-5-gtx',
    name: '나이키 페가수스 트레일 5 고어텍스',
    brand: 'Nike',
    category: '트레일',
    mileage: 0,
    maxMileage: 600,
    review: '리액트X 폼의 탄력과 고어텍스 방수, 강력한 올터레인 아웃솔로 험로와 젖은 임도에서도 미끄러짐 없음.',
    createdAt: '2026-01-10',
  },
  {
    id: 'shoe-nike-pegasus-plus',
    name: '나이키 페가수스 플러스',
    brand: 'Nike',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '전장 줌X 폼으로 재탄생한 페가수스 시리즈의 진화. 경쾌한 탄성과 다재다능한 주행감이 매력적.',
    createdAt: '2026-01-05',
  },

  // 2. 뉴발란스
  {
    id: 'shoe-nb-sc-trainer-v3',
    name: '뉴발란스 SC 트레이너 V3',
    brand: 'New Balance',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '퓨어셀 PEBA 폼과 카본 플레이트가 결합된 슈퍼 트레이너. 30km LSD 장거리 훈련 시 다리 피로도가 놀랍도록 적음.',
    createdAt: '2026-02-10',
  },
  {
    id: 'shoe-nb-sc-elite-v4',
    name: '뉴발란스 SC 엘리트 V4',
    brand: 'New Balance',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '100% PEBA 폼과 에너지 아크 기술로 발목이 편안하면서도 빠른 스피드를 보장하는 마라톤 레이싱화.',
    createdAt: '2026-03-05',
  },
  {
    id: 'shoe-nb-sc-pacer-v2',
    name: '뉴발란스 SC 페이서 V2',
    brand: 'New Balance',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '빠른 케이던스 전환과 단거리·10K 레이스에서 폭발적인 추진력을 선사하는 경량 카본 레이서.',
    createdAt: '2026-02-20',
  },

  // 3. 다이나핏
  {
    id: 'shoe-dynafit-sky-dna-carbon',
    name: '다이나핏 스카이 디엔에이 카본',
    brand: 'Dynafit',
    category: '트레일',
    mileage: 0,
    maxMileage: 600,
    review: '스카이라닝과 급경사 트레일 레이스용 카본 레이서. 험준한 산악 테크니컬 지형에서도 즉각적인 그립과 반발력 발휘.',
    createdAt: '2026-03-20',
  },

  // 4. 데상트
  {
    id: 'shoe-descente-deltapro-tempo-v2',
    name: '데상트 델타프로 템포 V2',
    brand: 'Descente',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '한국 러너의 족형에 최적화된 라스트와 템포런·빌드업 주행에 탄탄한 반발력을 제공하는 전천후 훈련화.',
    createdAt: '2026-02-01',
  },
  {
    id: 'shoe-descente-deltapro-exp-v2',
    name: '데상트 델타프로 EXP V2',
    brand: 'Descente',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '장거리 지속주에서 발의 뒤틀림을 완벽히 잡아주는 안정성과 풍부한 쿠셔닝의 익스피디션 트레이너.',
    createdAt: '2026-01-25',
  },

  // 5. 미즈노
  {
    id: 'shoe-mizuno-rebellion-pro-2',
    name: '미즈노 리벨리온 프로 2',
    brand: 'Mizuno',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '극단적인 스무스 스피드 어시스트 기하구조. 포어풋·미드풋 착지 시 강력한 롤링으로 페이스를 가속시킴.',
    createdAt: '2026-03-12',
  },
  {
    id: 'shoe-mizuno-neo-vista-2',
    name: '미즈노 네오 비스타 2',
    brand: 'Mizuno',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '부드러운 니트 어퍼와 에너지 NXT 폼, 나일론 플레이트의 조화로 구름 위를 달리는 듯한 쫀득한 쿠셔닝.',
    createdAt: '2026-02-18',
  },

  // 6. 브룩스
  {
    id: 'shoe-brooks-hyperion-max-3',
    name: '브룩스 하이페리온 맥스 3',
    brand: 'Brooks',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '질소 주입 DNA FLASH v2 폼과 빠른 롤링 구조로 다리 충격을 흡수하며 고속 순항을 돕는 맥스 트레이너.',
    createdAt: '2026-02-25',
  },
  {
    id: 'shoe-brooks-hyperion-elite-4-pb',
    name: '브룩스 하이페리온 엘리트 4 PB',
    brand: 'Brooks',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '100% PEBA 소재 DNA 고체 폼과 스피드볼트 카본 플레이트로 브룩스 역사상 가장 빠른 레이싱화.',
    createdAt: '2026-03-18',
  },

  // 7. 스케쳐스
  {
    id: 'shoe-skechers-aero-burst-slip-ins',
    name: '스케쳐스 에어로 버스트 (Slip Ins)',
    brand: 'Skechers',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '손을 대지 않고 쏙 들어가는 편리한 슬립인스 기술과 가볍고 탄력적인 에어로 쿠션으로 일상 조깅에 최고.',
    createdAt: '2026-01-15',
  },

  // 8. 써코니
  {
    id: 'shoe-saucony-endorphin-pro-4',
    name: '써코니 엔돌핀 프로 4',
    brand: 'Saucony',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: 'PWRRUN HG와 PB 듀얼 폼 구조의 환상적인 반발력. 스피드로롤 테크놀로지가 후반부 케이던스를 유지시켜줌.',
    createdAt: '2026-03-08',
  },
  {
    id: 'shoe-saucony-endorphin-elite-2-u',
    name: '써코니 엔돌핀 엘리트 2 U',
    brand: 'Saucony',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '써코니의 최상위 플래그십 레이서. 슬롯형 포크 카본 플레이트와 초고반발 파워런 HG로 극한의 스피드 지원.',
    createdAt: '2026-04-05',
  },
  {
    id: 'shoe-saucony-triumph-23',
    name: '써코니 트라이엄프 23',
    brand: 'Saucony',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '최상의 안락함을 제공하는 프리미엄 쿠션 조깅화. 장거리 회복주와 데일리 마일리지 누적의 든든한 동반자.',
    createdAt: '2026-01-08',
  },

  // 9. 아디다스
  {
    id: 'shoe-adidas-boston-13',
    name: '아디다스 보스턴 13',
    brand: 'Adidas',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '라이트스트라이크 프로 폼과 에너지로드의 황금비율. 템포런부터 30km 지속주까지 믿고 신는 국민 훈련화.',
    createdAt: '2026-02-05',
  },
  {
    id: 'shoe-adidas-adizero-evo-sl',
    name: '아디다스 아디제로 EVO SL',
    brand: 'Adidas',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '프로 EVO 1의 레이싱 DNA를 그대로 계승한 무플레이트 슈퍼 폼 트레이너. 깃털처럼 가볍고 탄력적임.',
    createdAt: '2026-03-02',
  },
  {
    id: 'shoe-adidas-y3-takumi-sen-10',
    name: '아디다스 Y-3 타쿠미센 10',
    brand: 'Adidas',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '요지 야마모토 감성의 미학적인 디자인과 타쿠미센 특유의 날카로운 5K~10K 트랙 스피드가 결합된 명작.',
    createdAt: '2026-02-22',
  },
  {
    id: 'shoe-adidas-adios-pro-4-dongma',
    name: '아디다스 아디제로 아디오스 프로 4 (동마)',
    brand: 'Adidas',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '동아일보 서울마라톤 한정 에디션! 새롭게 튜닝된 포어풋 로커와 라이트스트라이크 프로의 무결점 추진력.',
    createdAt: '2026-03-16',
  },
  {
    id: 'shoe-adidas-prime-x-2-strung',
    name: '아디다스 아디제로 프라임 X 2 스트렁',
    brand: 'Adidas',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '50mm 스택하이트 규정 파괴 슈퍼슈즈. 듀얼 카본 플레이트와 스트렁 갑피의 끝없는 트램펄린 반발력.',
    createdAt: '2026-01-30',
  },

  // 10. 아식스
  {
    id: 'shoe-asics-megablast',
    name: '아식스 메가블라스트',
    brand: 'Asics',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '슈퍼블라스트를 뛰어넘는 거대한 FF 터보 플러스 폼 볼륨. 다리 피로를 완벽 차단하는 궁극의 롱런 머신.',
    createdAt: '2026-02-12',
  },
  {
    id: 'shoe-asics-superblast-3',
    name: '아식스 슈퍼블라스트 3',
    brand: 'Asics',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '논카본 슈퍼 트레이너의 최정점. 가벼운 무게와 풍성한 쿠션으로 조깅부터 마라톤 페이스주까지 완벽 소화.',
    createdAt: '2026-01-18',
  },
  {
    id: 'shoe-asics-metaspeed-ray',
    name: '아식스 메타스피드 레이',
    brand: 'Asics',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '스트라이드 러너와 케이던스 러너를 모두 매료시키는 아식스의 최첨단 카본 레이서. 쾌속 질주감 선사.',
    createdAt: '2026-03-22',
  },

  // 11. 온 (On)
  {
    id: 'shoe-on-cloudboom-strike',
    name: '온 클라우드붐 스트라이크',
    brand: 'On',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '헬리온 HF 하이퍼 폼과 스푼형 카본 스피드보드의 조화. 매끄러운 롤링과 세련된 스위스 엔지니어링 레이서.',
    createdAt: '2026-03-10',
  },
  {
    id: 'shoe-on-cloudmonster-3-hyper',
    name: '온 클라우드몬스터 3 하이퍼',
    brand: 'On',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '괴물 같은 쿠셔닝과 에너지 반발력. 장거리 조깅과 템포 트레이닝에서 다리를 지치지 않게 보호해줌.',
    createdAt: '2026-02-08',
  },

  // 12. 푸마
  {
    id: 'shoe-puma-foreverrun-nitro-2',
    name: '푸마 포에버런 나이트로 2',
    brand: 'Puma',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '런가이드 시스템이 과내번을 안정적으로 보정해 주는 완벽한 가이드 레일 안정 쿠션화.',
    createdAt: '2026-01-22',
  },
  {
    id: 'shoe-puma-velocity-nitro-4',
    name: '푸마 벨로시티 나이트로 4',
    brand: 'Puma',
    category: '데일리',
    mileage: 0,
    maxMileage: 600,
    review: '가성비 최고의 데일리 러닝화. 푸마그립(PUMAGRIP)의 젖은 노면 접지력과 나이트로 폼의 부드러움이 일품.',
    createdAt: '2026-01-05',
  },
  {
    id: 'shoe-puma-deviate-nitro-2-ciele',
    name: '푸마 디비에이트 나이트로 2 씨엘르',
    brand: 'Puma',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '씨엘르 애슬레틱스와의 감각적인 콜라보 디자인. 이노플레이트 카본의 경쾌한 밀어주기가 돋보임.',
    createdAt: '2026-01-28',
  },
  {
    id: 'shoe-puma-deviate-nitro-4',
    name: '푸마 디비에이트 나이트로 4',
    brand: 'Puma',
    category: '장거리',
    mileage: 0,
    maxMileage: 600,
    review: '업그레이드된 나이트로 엘리트 폼 배합과 카본 파워플레이트. 데일리 스피드 트레이너의 최강자.',
    createdAt: '2026-02-14',
  },
  {
    id: 'shoe-puma-deviate-nitro-elite-4',
    name: '푸마 디비에이트 나이트로 엘리트 4',
    brand: 'Puma',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '초경량 모노메쉬 갑피와 100% 지방족 TPU/PEBA 나이트로 엘리트 폼. 풀코스 서브-3 도전을 위한 비밀 병기.',
    createdAt: '2026-03-06',
  },
  {
    id: 'shoe-puma-fast-r-nitro-elite-2',
    name: '푸마 패스트-R 나이트로 엘리트 2',
    brand: 'Puma',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '미래지향적인 분리형 미드솔과 돌출형 카본 파워플레이트. 도약 시 지면을 튕겨내는 가속력이 압도적.',
    createdAt: '2026-03-25',
  },

  // 13. 호카
  {
    id: 'shoe-hoka-mach-x2-wide',
    name: '호카 마하 X2 와이드',
    brand: 'Hoka',
    category: '스피드',
    mileage: 0,
    maxMileage: 600,
    review: '발볼이 넓은 러너도 편안한 와이드 핏. PEBA 폼과 Pebax 플레이트의 조화로 인터벌과 템포런에 최적.',
    createdAt: '2026-02-16',
  },
  {
    id: 'shoe-hoka-speedgoat-5-gtx',
    name: '호카 스피드고트 5 GTX',
    brand: 'Hoka',
    category: '트레일',
    mileage: 0,
    maxMileage: 600,
    review: '비브람 메가그립 트랙션 러그와 고어텍스 방수의 절대적인 신뢰감. 우천 산악 마라톤에서도 흔들림 없음.',
    createdAt: '2026-01-12',
  },
  {
    id: 'shoe-hoka-cielo-x1-2',
    name: '호카 씨엘로 X1 2.0',
    brand: 'Hoka',
    category: '레이싱',
    mileage: 0,
    maxMileage: 300,
    review: '호카 역사상 가장 에너지 효율이 높은 레이서. 윙드 카본 플레이트와 조기 메타로커로 피니시까지 지치지 않음.',
    createdAt: '2026-03-28',
  },
];
